### ISSUE TITLE
Bat Player crashes with stations missing certain metadata

### ISSUE THREAD

**Issue by PhillipAnd** [gabek/TheBatPlayerRoku#4]
[error.txt](https://github.com/gabek/TheBatPlayerRoku/files/76099/error.txt)
The attached error is encountered when listening to a radio station with no valid metadata.  I am currently investigating this issue further.

**Comment by gabek** [comment]
I think this should be fixed in that working branch I pushed up with an additional validity check:
https://github.com/gabek/TheBatPlayerRoku/blob/roku-directory/source/NowPlayingScreen.brs#L183

**Comment by PhillipAnd** [comment]
Confirmed that this fixes the issue.  Should I back-port this onto the master branch, or will the master branch and the roku-directory branch be merged soon?

**Comment by gabek** [comment]
It should really be in the master branch anyway, so go for it!  I'd like to say the roku-directory stuff will be merged in, but it's a largeish feature and a bug fix release is probably a better bet in the short term.

**Comment by PhillipAnd** [comment]
Would you mind making sure all your branches are pushed and up to date before I try to make sure all the bug fixes are in the master branch?

**Comment by gabek** [comment]
No problem!  I pushed up my copy of master.  That and roku-directory are the only two branches in-flight right now.  I removed the rest of the branches on github so it's not confusing.

**Comment by PhillipAnd** [comment]
fixed with pull request #5

**Comment by gabek** [comment]
Just submitted version 1.4.8 to Roku.  It consists of everything in master up to right now, including these fixes.
